development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "https://tinder-faye.herokuapp.com/faye"
  secret_token: "780af504d8b325a6f7e58fdad8033f8d19204aa511284816ef7665c94a01918a"
  signature_expiration: 3600 # one hour
